export const MOCK_BOOKS = [
  {
    id: 1,
    isbn: "978-7-111-12345-6",
    title: "深入理解计算机系统",
    author: "Randal E. Bryant",
    publisher: "机械工业出版社",
    category: "计算机科学",
    location: "A区-3F-01",
    total: 5,
    available: 4,
    cover: "",
    description: "本书从程序员的视角详细阐述计算机系统的本质概念。",
  },
  {
    id: 2,
    isbn: "978-7-302-45678-9",
    title: "算法导论",
    author: "Thomas H. Cormen",
    publisher: "清华大学出版社",
    category: "计算机科学",
    location: "A区-3F-02",
    total: 3,
    available: 1,
    cover: "",
    description: "算法领域的经典教材。",
  },
  {
    id: 3,
    isbn: "978-7-532-34567-8",
    title: "百年孤独",
    author: "加西亚·马尔克斯",
    publisher: "人民文学出版社",
    category: "文学",
    location: "B区-2F-01",
    total: 4,
    available: 4,
    cover: "",
    description: "魔幻现实主义文学的代表作。",
  },
  {
    id: 4,
    isbn: "978-7-542-56789-0",
    title: "人类简史",
    author: "尤瓦尔·赫拉利",
    publisher: "中信出版社",
    category: "历史",
    location: "B区-2F-05",
    total: 3,
    available: 3,
    cover: "",
    description: "从动物到上帝。",
  },
  {
    id: 5,
    isbn: "978-7-300-23456-7",
    title: "经济学原理",
    author: "曼昆",
    publisher: "中国人民大学出版社",
    category: "经济管理",
    location: "C区-3F-03",
    total: 6,
    available: 5,
    cover: "",
    description: "经济学入门经典教材。",
  },
  {
    id: 6,
    isbn: "978-7-111-11111-1",
    title: "Python编程从入门到实践",
    author: "Eric Matthes",
    publisher: "人民邮电出版社",
    category: "计算机科学",
    location: "A区-3F-03",
    total: 4,
    available: 4,
    cover: "",
    description: "零基础学习Python编程。",
  },
  {
    id: 7,
    isbn: "978-7-302-22222-2",
    title: "数据结构与算法分析",
    author: "Mark Allen Weiss",
    publisher: "机械工业出版社",
    category: "计算机科学",
    location: "A区-3F-02",
    total: 3,
    available: 3,
    cover: "",
    description: "系统介绍数据结构和算法分析核心知识。",
  },
  {
    id: 8,
    isbn: "978-7-533-33333-3",
    title: "活着",
    author: "余华",
    publisher: "作家出版社",
    category: "文学",
    location: "B区-2F-02",
    total: 5,
    available: 5,
    cover: "",
    description: "讲述了农村人福贵悲惨的人生遭遇。",
  },
  {
    id: 9,
    isbn: "978-7-544-44444-4",
    title: "明朝那些事儿",
    author: "当年明月",
    publisher: "中国海关出版社",
    category: "历史",
    location: "B区-2F-05",
    total: 4,
    available: 4,
    cover: "",
    description: "幽默风趣的语言讲述明朝三百年历史。",
  },
  {
    id: 10,
    isbn: "978-7-555-55555-5",
    title: "国富论",
    author: "亚当·斯密",
    publisher: "商务印书馆",
    category: "经济管理",
    location: "C区-3F-03",
    total: 2,
    available: 1,
    cover: "",
    description: "现代经济学之父的经典著作。",
  },
];

export const MOCK_BOOKS_AVIATION = [
  {
    id: 11,
    isbn: "978-7-118-11111-1",
    title: "航空发动机原理",
    author: "刘大响",
    publisher: "航空工业出版社",
    category: "工程技术",
    location: "D区-5F-01",
    total: 3,
    available: 2,
    cover: "",
    description: "系统介绍航空燃气涡轮发动机的工作原理与结构设计。",
  },
  {
    id: 12,
    isbn: "978-7-118-22222-2",
    title: "飞机总体设计",
    author: "杨超",
    publisher: "北京航空航天大学出版社",
    category: "工程技术",
    location: "D区-5F-02",
    total: 2,
    available: 2,
    cover: "",
    description: "全面讲解飞机总体设计的理论与方法。",
  },
  {
    id: 13,
    isbn: "978-7-118-33333-3",
    title: "航空电子系统",
    author: "王永生",
    publisher: "国防工业出版社",
    category: "工程技术",
    location: "D区-5F-03",
    total: 4,
    available: 3,
    cover: "",
    description: "介绍航空电子系统的架构、设计与应用。",
  },
  {
    id: 14,
    isbn: "978-7-118-44444-4",
    title: "飞行力学",
    author: "方振平",
    publisher: "航空工业出版社",
    category: "自然科学",
    location: "D区-5F-04",
    total: 3,
    available: 1,
    cover: "",
    description: "阐述飞行器的运动规律与控制方法。",
  },
  {
    id: 15,
    isbn: "978-7-118-55555-5",
    title: "航空航天概论",
    author: "贾玉红",
    publisher: "北京航空航天大学出版社",
    category: "工程技术",
    location: "D区-5F-05",
    total: 5,
    available: 4,
    cover: "",
    description: "全面介绍航空航天领域的基础知识和发展历程。",
  },
];

export const MOCK_BORROW_RECORDS = [
  {
    id: 1,
    borrowDate: "2026-04-20",
    dueDate: "2026-05-20",
    returnDate: null,
    status: "borrowed",
    renewed: false,
    book: {
      id: 1,
      title: "深入理解计算机系统",
      author: "Randal E. Bryant",
      cover: "",
    },
    bookTitle: "深入理解计算机系统",
  },
  {
    id: 2,
    borrowDate: "2026-05-01",
    dueDate: "2026-06-01",
    returnDate: null,
    status: "borrowed",
    renewed: true,
    book: {
      id: 6,
      title: "Python编程从入门到实践",
      author: "Eric Matthes",
      cover: "",
    },
    bookTitle: "Python编程从入门到实践",
  },
  {
    id: 3,
    borrowDate: "2026-03-15",
    dueDate: "2026-04-15",
    returnDate: null,
    status: "overdue",
    renewed: false,
    book: { id: 3, title: "百年孤独", author: "加西亚·马尔克斯", cover: "" },
    bookTitle: "百年孤独",
  },
  {
    id: 4,
    borrowDate: "2026-05-10",
    dueDate: "2026-06-10",
    returnDate: null,
    status: "borrowed",
    renewed: false,
    book: { id: 11, title: "航空发动机原理", author: "刘大响", cover: "" },
    bookTitle: "航空发动机原理",
  },
];

export const MOCK_USERS = [
  { studentId: "20200001", password: "123456", name: "张三" },
  { studentId: "20200002", password: "123456", name: "李四" },
];
